Field(int, A)
Field(float, B)
Field(char, C)
Field(double, Padding1)
Field(float, Padding2)
Field(double, Padding3)
Field(std::string, Name)

FieldArray(int, IntArray, 30)
FieldArray(char, CharArray, 15)
